import { useState } from 'react';
import Layout from '../components/Layout';
import { Spinner } from '../components/UI';

const OBJECTIVES = ['Brand Awareness','Product Launch','Sales Drive','Event Promotion','App Downloads','Lead Generation','Rebranding','Market Entry'];
const CATEGORIES = ['Television','Radio','Podcasts','Out-of-Home','Print & Digital','Influencers'];
const BUDGETS    = ['Under ₦500k','₦500k – ₦2M','₦2M – ₦5M','₦5M – ₦10M','₦10M – ₦25M','₦25M+'];
const DURATIONS  = ['1 week','2 weeks','1 month','6 weeks','2 months','3 months','6 months'];
const REGIONS    = ['Lagos','Abuja','Port Harcourt','Kano','Enugu','Ibadan','Nationwide'];

export default function BriefGenerator() {
  const [step, setStep]       = useState(1);
  const [form, setForm]       = useState({ brandName:'', industry:'', product:'', objective:'', targetAudience:'', budget:'', duration:'', regions:[], channels:[], extraContext:'' });
  const [loading, setLoading] = useState(false);
  const [brief, setBrief]     = useState(null);
  const [error, setError]     = useState('');
  const [copied, setCopied]   = useState(false);

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));
  const toggle = (k, v) => setForm(f => ({ ...f, [k]: f[k].includes(v) ? f[k].filter(x => x !== v) : [...f[k], v] }));

  const generate = async () => {
    setLoading(true); setError(''); setBrief(null);
    try {
      const prompt = `You are BrandCasta's senior media strategist in Nigeria. Generate a comprehensive, professional campaign brief for the following brand.

BRAND DETAILS:
- Brand Name: ${form.brandName}
- Industry: ${form.industry}
- Product/Service: ${form.product}
- Campaign Objective: ${form.objective}
- Target Audience: ${form.targetAudience}
- Budget Range: ${form.budget}
- Campaign Duration: ${form.duration}
- Target Regions: ${form.regions.join(', ') || 'Nationwide'}
- Preferred Media Channels: ${form.channels.join(', ') || 'All channels'}
- Additional Context: ${form.extraContext || 'None'}

Generate a detailed campaign brief with these exact sections, using this JSON structure:
{
  "executiveSummary": "2-3 sentence overview of the campaign strategy",
  "campaignObjectives": ["objective 1", "objective 2", "objective 3"],
  "targetAudience": {
    "primary": "Primary audience description",
    "secondary": "Secondary audience description",
    "psychographics": "Psychographic profile",
    "mediaConsumption": "How they consume media"
  },
  "mediaStrategy": [
    {
      "channel": "channel name",
      "rationale": "why this channel",
      "allocation": "% of budget",
      "formats": ["format 1", "format 2"],
      "recommendedProviders": ["provider 1", "provider 2"]
    }
  ],
  "budgetBreakdown": [
    { "line": "line item", "allocation": "₦ amount or %", "notes": "notes" }
  ],
  "timeline": [
    { "phase": "Phase name", "weeks": "Week 1-2", "activities": ["activity 1", "activity 2"] }
  ],
  "creativeDirection": {
    "keyMessage": "The single most important message",
    "tone": "Tone and style guidance",
    "callToAction": "Primary CTA",
    "creativeRequirements": ["req 1", "req 2", "req 3"]
  },
  "kpis": [
    { "metric": "KPI name", "target": "target value", "measurement": "how to measure" }
  ],
  "risks": [
    { "risk": "risk description", "mitigation": "mitigation strategy" }
  ]
}

Respond with ONLY valid JSON. No markdown, no explanation, no backticks. Make recommendations specific to Nigerian media market. Reference real Nigerian media providers where applicable (Channels TV, Cool FM, Punch, etc.).`;

      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 1000,
          messages: [{ role: 'user', content: prompt }],
        }),
      });
      const data = await response.json();
      const text = data.content?.map(c => c.text || '').join('').trim();
      const clean = text.replace(/```json|```/g, '').trim();
      const parsed = JSON.parse(clean);
      setBrief(parsed);
      setStep(3);
    } catch(e) { setError('Failed to generate brief. Please try again.'); console.error(e); }
    finally { setLoading(false); }
  };

  const copy = () => {
    if (!brief) return;
    const text = `CAMPAIGN BRIEF — ${form.brandName.toUpperCase()}
Generated by BrandCasta

EXECUTIVE SUMMARY
${brief.executiveSummary}

OBJECTIVES
${brief.campaignObjectives?.map((o,i) => `${i+1}. ${o}`).join('\n')}

TARGET AUDIENCE
Primary: ${brief.targetAudience?.primary}
Secondary: ${brief.targetAudience?.secondary}
Psychographics: ${brief.targetAudience?.psychographics}
Media Consumption: ${brief.targetAudience?.mediaConsumption}

MEDIA STRATEGY
${brief.mediaStrategy?.map(m => `• ${m.channel} (${m.allocation})\n  ${m.rationale}\n  Formats: ${m.formats?.join(', ')}\n  Providers: ${m.recommendedProviders?.join(', ')}`).join('\n\n')}

BUDGET BREAKDOWN
${brief.budgetBreakdown?.map(b => `• ${b.line}: ${b.allocation} — ${b.notes}`).join('\n')}

TIMELINE
${brief.timeline?.map(t => `${t.phase} (${t.weeks})\n${t.activities?.map(a => `  • ${a}`).join('\n')}`).join('\n\n')}

CREATIVE DIRECTION
Key Message: ${brief.creativeDirection?.keyMessage}
Tone: ${brief.creativeDirection?.tone}
CTA: ${brief.creativeDirection?.callToAction}

KPIs
${brief.kpis?.map(k => `• ${k.metric}: ${k.target} (${k.measurement})`).join('\n')}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const inp = { width:'100%', padding:'11px 14px', borderRadius:10, fontSize:13, outline:'none', background:'rgba(255,255,255,0.05)', border:'1px solid var(--border)', color:'white', fontFamily:'Manrope,sans-serif', boxSizing:'border-box' };
  const pill = (active) => ({ padding:'7px 14px', borderRadius:20, fontSize:12, fontWeight:600, cursor:'pointer', transition:'all 0.15s', border:'none', background: active ? 'rgba(99,102,241,0.2)' : 'rgba(255,255,255,0.04)', color: active ? '#a5b4fc' : 'rgba(255,255,255,0.5)', outline: active ? '1px solid rgba(99,102,241,0.4)' : '1px solid rgba(255,255,255,0.08)' });

  return (
    <Layout title="AI Brief Generator" subtitle="Generate a professional campaign brief powered by Claude AI">

      {/* Progress */}
      <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:28 }}>
        {['Brand Details','Strategy Inputs','Your Brief'].map((label, i) => {
          const s = i + 1; const active = step === s; const done = step > s;
          return (
            <div key={s} style={{ display:'flex', alignItems:'center', flex: i < 2 ? 1 : 'none' }}>
              <div style={{ display:'flex', alignItems:'center', gap:8, flexShrink:0 }}>
                <div style={{ width:26, height:26, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center', fontSize:11, fontWeight:700,
                  background: done ? 'linear-gradient(135deg,#6366f1,#a855f7)' : active ? 'rgba(99,102,241,0.15)' : 'rgba(255,255,255,0.04)',
                  border: active ? '1px solid rgba(99,102,241,0.4)' : done ? 'none' : '1px solid var(--border)',
                  color: done || active ? 'white' : 'var(--text-muted)',
                }}>{done ? '✓' : s}</div>
                <span style={{ fontSize:12, fontWeight:600, color: active ? 'white' : done ? '#a5b4fc' : 'var(--text-muted)', whiteSpace:'nowrap' }}>{label}</span>
              </div>
              {i < 2 && <div style={{ flex:1, height:1, background: done ? 'rgba(99,102,241,0.4)' : 'var(--border)', margin:'0 10px' }}/>}
            </div>
          );
        })}
      </div>

      <div className="max-w-2xl">

        {/* STEP 1 */}
        {step === 1 && (
          <div className="page-card" style={{ padding:28 }}>
            <p style={{ fontWeight:700, fontSize:16, color:'white', marginBottom:4 }}>Tell us about the brand</p>
            <p style={{ fontSize:13, color:'var(--text-muted)', marginBottom:24 }}>The more detail you provide, the better the brief.</p>
            <div className="space-y-4">
              <div>
                <label className="form-label">Brand Name *</label>
                <input style={inp} placeholder="e.g. Indomie Nigeria" value={form.brandName} onChange={e => set('brandName', e.target.value)}/>
              </div>
              <div>
                <label className="form-label">Industry / Sector *</label>
                <input style={inp} placeholder="e.g. FMCG, Fintech, Telecoms, Real Estate" value={form.industry} onChange={e => set('industry', e.target.value)}/>
              </div>
              <div>
                <label className="form-label">Product or Service being advertised *</label>
                <input style={inp} placeholder="e.g. Indomie Stir-Fry variant launch" value={form.product} onChange={e => set('product', e.target.value)}/>
              </div>
              <div>
                <label className="form-label">Target Audience *</label>
                <textarea rows={3} style={{ ...inp, resize:'vertical' }} placeholder="e.g. Urban Nigerian youth aged 18-35, middle income, active on social media, frequent noodle consumers" value={form.targetAudience} onChange={e => set('targetAudience', e.target.value)}/>
              </div>
              <div>
                <label className="form-label">Additional Context</label>
                <textarea rows={3} style={{ ...inp, resize:'vertical' }} placeholder="Any specific requirements, past campaign insights, competitor context, seasonal factors, cultural moments to leverage..." value={form.extraContext} onChange={e => set('extraContext', e.target.value)}/>
              </div>
            </div>
            <div className="flex justify-end mt-6">
              <button onClick={() => { if (!form.brandName||!form.industry||!form.product||!form.targetAudience) return; setStep(2); }} className="btn-primary" style={{ padding:'10px 24px' }}>
                Next →
              </button>
            </div>
          </div>
        )}

        {/* STEP 2 */}
        {step === 2 && (
          <div className="page-card" style={{ padding:28 }}>
            <p style={{ fontWeight:700, fontSize:16, color:'white', marginBottom:4 }}>Campaign strategy inputs</p>
            <p style={{ fontSize:13, color:'var(--text-muted)', marginBottom:24 }}>Help us understand your campaign parameters.</p>
            <div className="space-y-5">

              <div>
                <label className="form-label">Campaign Objective *</label>
                <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
                  {OBJECTIVES.map(o => <button key={o} onClick={() => set('objective', o)} style={pill(form.objective===o)}>{o}</button>)}
                </div>
              </div>

              <div>
                <label className="form-label">Budget Range *</label>
                <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
                  {BUDGETS.map(b => <button key={b} onClick={() => set('budget', b)} style={pill(form.budget===b)}>{b}</button>)}
                </div>
              </div>

              <div>
                <label className="form-label">Campaign Duration</label>
                <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
                  {DURATIONS.map(d => <button key={d} onClick={() => set('duration', d)} style={pill(form.duration===d)}>{d}</button>)}
                </div>
              </div>

              <div>
                <label className="form-label">Target Regions (select all that apply)</label>
                <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
                  {REGIONS.map(r => <button key={r} onClick={() => toggle('regions', r)} style={pill(form.regions.includes(r))}>{r}</button>)}
                </div>
              </div>

              <div>
                <label className="form-label">Preferred Media Channels (select all that apply)</label>
                <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
                  {CATEGORIES.map(c => <button key={c} onClick={() => toggle('channels', c)} style={pill(form.channels.includes(c))}>{c}</button>)}
                </div>
              </div>
            </div>

            {error && <p style={{ color:'#fca5a5', fontSize:12, marginTop:12 }}>{error}</p>}

            <div className="flex gap-3 mt-6">
              <button onClick={() => setStep(1)} className="btn-secondary" style={{ padding:'10px 20px' }}>← Back</button>
              <button onClick={() => { if (!form.objective||!form.budget) return; generate(); }} disabled={loading} className="btn-primary" style={{ flex:1, justifyContent:'center', padding:'10px' }}>
                {loading ? <><Spinner size={14}/> Generating brief…</> : '✨ Generate Campaign Brief'}
              </button>
            </div>
          </div>
        )}

        {/* STEP 3 — BRIEF OUTPUT */}
        {step === 3 && brief && (
          <div className="space-y-4">

            {/* Header */}
            <div style={{ padding:'20px 24px', borderRadius:14, background:'linear-gradient(135deg,rgba(99,102,241,0.12),rgba(168,85,247,0.08))', border:'1px solid rgba(99,102,241,0.25)', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
              <div>
                <p style={{ fontWeight:800, fontSize:17, color:'white', letterSpacing:'-0.3px' }}>Campaign Brief — {form.brandName}</p>
                <p style={{ fontSize:12, color:'var(--text-muted)', marginTop:3 }}>Generated by BrandCasta AI · {new Date().toLocaleDateString('en-NG',{day:'numeric',month:'long',year:'numeric'})}</p>
              </div>
              <div style={{ display:'flex', gap:8 }}>
                <button onClick={copy} className="btn-secondary" style={{ fontSize:12, padding:'7px 14px' }}>
                  {copied ? '✓ Copied' : '📋 Copy'}
                </button>
                <button onClick={() => { setBrief(null); setStep(1); setForm({ brandName:'', industry:'', product:'', objective:'', targetAudience:'', budget:'', duration:'', regions:[], channels:[], extraContext:'' }); }} className="btn-secondary" style={{ fontSize:12, padding:'7px 14px' }}>New Brief</button>
              </div>
            </div>

            {/* Executive Summary */}
            <div className="page-card" style={{ padding:22 }}>
              <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:10 }}>Executive Summary</p>
              <p style={{ fontSize:14, color:'rgba(255,255,255,0.8)', lineHeight:1.8 }}>{brief.executiveSummary}</p>
            </div>

            {/* Objectives + Audience */}
            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14 }}>
              <div className="page-card" style={{ padding:22 }}>
                <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>Campaign Objectives</p>
                {brief.campaignObjectives?.map((o, i) => (
                  <div key={i} style={{ display:'flex', gap:10, marginBottom:8 }}>
                    <span style={{ width:20, height:20, borderRadius:'50%', background:'rgba(99,102,241,0.15)', color:'#a5b4fc', fontSize:10, fontWeight:700, display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0, marginTop:1 }}>{i+1}</span>
                    <p style={{ fontSize:13, color:'rgba(255,255,255,0.75)', lineHeight:1.6 }}>{o}</p>
                  </div>
                ))}
              </div>
              <div className="page-card" style={{ padding:22 }}>
                <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>Target Audience</p>
                {[['Primary', brief.targetAudience?.primary],['Secondary', brief.targetAudience?.secondary],['Psychographics', brief.targetAudience?.psychographics],['Media Habits', brief.targetAudience?.mediaConsumption]].map(([l,v]) => v && (
                  <div key={l} style={{ marginBottom:10 }}>
                    <p style={{ fontSize:10, fontWeight:700, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em' }}>{l}</p>
                    <p style={{ fontSize:12, color:'rgba(255,255,255,0.7)', lineHeight:1.6, marginTop:3 }}>{v}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Media Strategy */}
            <div className="page-card" style={{ padding:22 }}>
              <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:14 }}>Media Strategy</p>
              <div className="space-y-3">
                {brief.mediaStrategy?.map((m, i) => (
                  <div key={i} style={{ padding:'14px 16px', borderRadius:10, background:'rgba(255,255,255,0.03)', border:'1px solid var(--border)' }}>
                    <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:8 }}>
                      <p style={{ fontWeight:700, fontSize:14, color:'white' }}>{m.channel}</p>
                      <span style={{ padding:'3px 10px', borderRadius:20, background:'rgba(99,102,241,0.15)', color:'#a5b4fc', fontSize:11, fontWeight:700 }}>{m.allocation}</span>
                    </div>
                    <p style={{ fontSize:13, color:'rgba(255,255,255,0.6)', marginBottom:8, lineHeight:1.6 }}>{m.rationale}</p>
                    <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
                      {m.formats?.map(f => <span key={f} style={{ padding:'2px 8px', borderRadius:6, background:'rgba(255,255,255,0.05)', color:'rgba(255,255,255,0.5)', fontSize:11 }}>{f}</span>)}
                    </div>
                    {m.recommendedProviders?.length > 0 && (
                      <div style={{ marginTop:8 }}>
                        <p style={{ fontSize:10, color:'var(--text-muted)', fontWeight:600, marginBottom:4 }}>RECOMMENDED PROVIDERS</p>
                        <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
                          {m.recommendedProviders.map(p => <span key={p} style={{ padding:'2px 8px', borderRadius:6, background:'rgba(20,184,166,0.08)', border:'1px solid rgba(20,184,166,0.15)', color:'#5eead4', fontSize:11 }}>{p}</span>)}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Budget + Timeline */}
            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14 }}>
              <div className="page-card" style={{ padding:22 }}>
                <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>Budget Breakdown</p>
                {brief.budgetBreakdown?.map((b, i) => (
                  <div key={i} style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', padding:'8px 0', borderBottom:'1px solid rgba(255,255,255,0.05)' }}>
                    <div>
                      <p style={{ fontSize:13, color:'white', fontWeight:600 }}>{b.line}</p>
                      {b.notes && <p style={{ fontSize:11, color:'var(--text-muted)', marginTop:2 }}>{b.notes}</p>}
                    </div>
                    <span style={{ fontSize:13, fontWeight:700, color:'#a5b4fc', flexShrink:0, marginLeft:8 }}>{b.allocation}</span>
                  </div>
                ))}
              </div>
              <div className="page-card" style={{ padding:22 }}>
                <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>Campaign Timeline</p>
                {brief.timeline?.map((t, i) => (
                  <div key={i} style={{ marginBottom:12 }}>
                    <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:4 }}>
                      <span style={{ padding:'2px 8px', borderRadius:6, background:'rgba(99,102,241,0.12)', color:'#a5b4fc', fontSize:10, fontWeight:700 }}>{t.weeks}</span>
                      <p style={{ fontSize:13, fontWeight:600, color:'white' }}>{t.phase}</p>
                    </div>
                    {t.activities?.map(a => <p key={a} style={{ fontSize:12, color:'rgba(255,255,255,0.5)', paddingLeft:8, marginBottom:2 }}>• {a}</p>)}
                  </div>
                ))}
              </div>
            </div>

            {/* Creative Direction */}
            <div className="page-card" style={{ padding:22 }}>
              <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:14 }}>Creative Direction</p>
              <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:12, marginBottom:14 }}>
                {[['Key Message', brief.creativeDirection?.keyMessage],['Tone & Style', brief.creativeDirection?.tone],['Call to Action', brief.creativeDirection?.callToAction]].map(([l,v]) => (
                  <div key={l} style={{ padding:'12px 14px', borderRadius:10, background:'rgba(255,255,255,0.03)', border:'1px solid var(--border)' }}>
                    <p style={{ fontSize:10, fontWeight:700, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:6 }}>{l}</p>
                    <p style={{ fontSize:13, color:'rgba(255,255,255,0.8)', lineHeight:1.6 }}>{v}</p>
                  </div>
                ))}
              </div>
              <div>
                <p style={{ fontSize:11, fontWeight:700, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:8 }}>Creative Requirements</p>
                <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
                  {brief.creativeDirection?.creativeRequirements?.map(r => (
                    <span key={r} style={{ padding:'4px 10px', borderRadius:8, background:'rgba(255,255,255,0.05)', border:'1px solid rgba(255,255,255,0.08)', color:'rgba(255,255,255,0.6)', fontSize:12 }}>{r}</span>
                  ))}
                </div>
              </div>
            </div>

            {/* KPIs + Risks */}
            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14 }}>
              <div className="page-card" style={{ padding:22 }}>
                <p style={{ fontSize:11, fontWeight:700, color:'#a5b4fc', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>KPIs & Success Metrics</p>
                {brief.kpis?.map((k, i) => (
                  <div key={i} style={{ padding:'10px 12px', borderRadius:9, background:'rgba(255,255,255,0.03)', border:'1px solid var(--border)', marginBottom:8 }}>
                    <p style={{ fontWeight:700, fontSize:13, color:'white' }}>{k.metric}</p>
                    <p style={{ fontSize:12, color:'#a5b4fc', fontWeight:600, marginTop:2 }}>Target: {k.target}</p>
                    <p style={{ fontSize:11, color:'var(--text-muted)', marginTop:2 }}>{k.measurement}</p>
                  </div>
                ))}
              </div>
              <div className="page-card" style={{ padding:22 }}>
                <p style={{ fontSize:11, fontWeight:700, color:'#fca5a5', textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>Risk & Mitigation</p>
                {brief.risks?.map((r, i) => (
                  <div key={i} style={{ padding:'10px 12px', borderRadius:9, background:'rgba(239,68,68,0.04)', border:'1px solid rgba(239,68,68,0.1)', marginBottom:8 }}>
                    <p style={{ fontWeight:600, fontSize:13, color:'rgba(255,255,255,0.8)' }}>{r.risk}</p>
                    <p style={{ fontSize:12, color:'rgba(255,255,255,0.45)', marginTop:4, lineHeight:1.5 }}>↳ {r.mitigation}</p>
                  </div>
                ))}
              </div>
            </div>

            <div style={{ display:'flex', gap:10, justifyContent:'flex-end' }}>
              <button onClick={copy} className="btn-secondary" style={{ fontSize:13 }}>{copied ? '✓ Copied to clipboard' : '📋 Copy Full Brief'}</button>
              <button onClick={() => { setStep(2); setBrief(null); }} className="btn-primary" style={{ fontSize:13, padding:'10px 20px' }}>✨ Regenerate</button>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}